package admin

import (
	"net/http"

	"github.com/koopa0/goen/internal/admin/access"
)

func (h *Handler) Routes(mux *http.ServeMux, ac *access.Control) {
	mux.HandleFunc("GET /admin", ac.RequireStaff(h.Dashboard))
	mux.HandleFunc("GET /admin/orders", ac.RequireStaff(h.Orders))
	mux.HandleFunc("GET /admin/orders/{number}", ac.RequireStaff(h.Order))
	mux.HandleFunc("POST /admin/orders/{number}/status", ac.RequireStaff(h.AdvanceOrder))
	mux.HandleFunc("POST /admin/orders/{number}/refund", ac.RequireStaff(h.RefundBeforeShipment))
	mux.HandleFunc("POST /admin/orders/{number}/ship", ac.RequireStaff(h.Ship))
	mux.HandleFunc("POST /admin/orders/{number}/note", ac.RequireStaff(h.StaffNote))
	mux.HandleFunc("POST /admin/orders/{number}/delivery", ac.RequireStaff(h.CorrectDelivery))
	mux.HandleFunc("GET /admin/products", ac.RequireStaff(h.Products))
	mux.HandleFunc("POST /admin/products", ac.RequireStaff(h.CreateProduct))
	mux.HandleFunc("GET /admin/products/new", ac.RequireStaff(h.NewProduct))
	mux.HandleFunc("GET /admin/products/{slug}", ac.RequireStaff(h.EditProduct))
	mux.HandleFunc("POST /admin/products/{slug}", ac.RequireStaff(h.UpdateProduct))
	mux.HandleFunc("POST /admin/products/{slug}/status", ac.RequireStaff(h.PublishProduct))
	mux.HandleFunc("POST /admin/products/{slug}/variants", ac.RequireStaff(h.AddVariant))
	mux.HandleFunc("GET /admin/stock", ac.RequireStaff(h.Variants))
	mux.HandleFunc("GET /admin/stock/{sku}", ac.RequireStaff(h.Movements))
	mux.HandleFunc("POST /admin/stock/adjust", ac.RequireStaff(h.AdjustStock))
	mux.HandleFunc("POST /admin/stock/receive", ac.RequireStaff(h.ReceiveStock))
	mux.HandleFunc("POST /admin/stock/active", ac.RequireStaff(h.SetVariantActive))
	mux.HandleFunc("POST /admin/stock/price", ac.RequireStaff(h.SetVariantPrice))
	mux.HandleFunc("GET /admin/returns", ac.RequireStaff(h.Returns))
	mux.HandleFunc("POST /admin/returns/{id}/decide", ac.RequireStaff(h.Decide))
	mux.HandleFunc("POST /admin/returns/{id}/assess", ac.RequireStaff(h.Assess))
	mux.HandleFunc("POST /admin/returns/{id}/inspect", ac.RequireStaff(h.Inspect))
	mux.HandleFunc("POST /admin/returns/{id}/complete", ac.RequireStaff(h.Complete))
	mux.HandleFunc("POST /admin/orders/{number}/invoice", ac.RequireStaff(h.IssueInvoice))
	mux.HandleFunc("POST /admin/orders/{number}/invoice/void", ac.RequireStaff(h.VoidInvoice))
	mux.HandleFunc("POST /admin/orders/{number}/invoice/allowance", ac.RequireStaff(h.AllowInvoice))
	mux.HandleFunc("POST /admin/products/{slug}/options", ac.RequireStaff(h.AddOption))
	mux.HandleFunc("POST /admin/products/{slug}/options/values", ac.RequireStaff(h.AddOptionValue))
	mux.HandleFunc("POST /admin/products/{slug}/specs", ac.RequireStaff(h.AddSpec))
	mux.HandleFunc("POST /admin/products/{slug}/specs/remove", ac.RequireStaff(h.RemoveSpec))
	mux.HandleFunc("POST /admin/products/{slug}/images", ac.RequireStaff(h.UploadImage))
	mux.HandleFunc("POST /admin/products/{slug}/images/reuse", ac.RequireStaff(h.ReuseImage))
	mux.HandleFunc("POST /admin/products/{slug}/images/remove", ac.RequireStaff(h.RemoveImage))
	mux.HandleFunc("POST /admin/products/{slug}/images/option", ac.RequireStaff(h.SetImageOption))
	mux.HandleFunc("POST /admin/products/{slug}/images/move", ac.RequireStaff(h.MoveImage))
	mux.HandleFunc("GET /admin/shipping", ac.RequireStaff(h.Shipping))
	mux.HandleFunc("POST /admin/shipping/version", ac.RequireStaff(h.PublishShippingVersion))
	mux.HandleFunc("POST /admin/shipping/surcharge", ac.RequireStaff(h.SetZoneSurcharge))
	mux.HandleFunc("POST /admin/shipping/method", ac.RequireStaff(h.CreateShippingMethod))
	mux.HandleFunc("POST /admin/shipping/method/{id}/active", ac.RequireStaff(h.SetShippingMethodActive))
	mux.HandleFunc("POST /admin/shipping/zone", ac.RequireStaff(h.CreateShippingZone))
	mux.HandleFunc("POST /admin/shipping/zone/{id}/prefixes", ac.RequireStaff(h.SetZonePrefixes))
	mux.HandleFunc("POST /admin/shipping/zone/{id}/delete", ac.RequireStaff(h.DeleteShippingZone))
	mux.HandleFunc("GET /admin/faq", ac.RequireStaff(h.FAQ))
	mux.HandleFunc("POST /admin/faq", ac.RequireStaff(h.CreateFAQEntry))
	mux.HandleFunc("POST /admin/faq/{id}", ac.RequireStaff(h.EditFAQEntry))
	mux.HandleFunc("GET /admin/newsletter", ac.RequireStaff(h.Newsletter))
	mux.HandleFunc("POST /admin/newsletter", ac.RequireStaff(h.ComposeNewsletter))
	mux.HandleFunc("POST /admin/newsletter/{id}/send", ac.RequireStaff(h.SendNewsletter))
	mux.HandleFunc("GET /admin/taxonomy", ac.RequireStaff(h.Taxonomy))
	mux.HandleFunc("POST /admin/taxonomy/{kind}", ac.RequireStaff(h.CreateTaxon))
	mux.HandleFunc("POST /admin/taxonomy/{kind}/{slug}", ac.RequireStaff(h.EditTaxon))
	mux.HandleFunc("GET /admin/categories/{slug}", ac.RequireStaff(h.EditCategory))
	mux.HandleFunc("POST /admin/categories/{slug}/image", ac.RequireStaff(h.SetCategoryImage))
	mux.HandleFunc("POST /admin/categories/{slug}/image/remove", ac.RequireStaff(h.RemoveCategoryImage))
	mux.HandleFunc("GET /admin/home", ac.RequireStaff(h.HomeContent))
	mux.HandleFunc("POST /admin/home", ac.RequireStaff(h.CreateHeroSlide))
	mux.HandleFunc("POST /admin/home/banner", ac.RequireStaff(h.CreateBanner))
	mux.HandleFunc("POST /admin/home/banner/{id}/active", ac.RequireStaff(h.SetBannerActive))
	mux.HandleFunc("POST /admin/home/{id}/active", ac.RequireStaff(h.SetHeroSlideActive))
	mux.HandleFunc("POST /admin/home/{id}/promote", ac.RequireStaff(h.PromoteHeroSlide))
}
