package i18n

var (
	KeyMailOrderCancelledSubject            = key("mail.order.cancelled.subject", Message{ZhHant: "訂單 %s 已取消", En: "Order %s cancelled"})
	KeyMailOrderCustomerCancelledBody       = key("mail.order.cancelled.customer.body", Message{ZhHant: "你已取消訂單 %s。這筆訂單尚未收款；若有使用購物金，已退回你的帳戶。查看訂單：\n%s", En: "You cancelled order %s. It was not charged, and any store credit you applied has been returned to your account. View your order:\n%s"})
	KeyMailOrderDeadlineCancelledBody       = key("mail.order.cancelled.deadline.body", Message{ZhHant: "訂單 %s 在保留時間內沒有完成付款，已自動取消。這筆訂單沒有收取任何款項；若有使用購物金，已退回你的帳戶。查看訂單：\n%s", En: "Order %s was not paid while its stock was held, so it has been cancelled automatically. Nothing was charged, and any store credit you applied has been returned to your account. View your order:\n%s"})
	KeyMailOrderCustomerCancelledRefundBody = key("mail.order.cancelled.customer.refund.body", Message{ZhHant: "你已取消訂單 %s。若有款項已經到帳，已經或將會全額退還給你；若有使用購物金，已退回你的帳戶。查看訂單：\n%s", En: "You cancelled order %s. If a payment reached us, it has been or will be refunded in full, and any store credit you applied has been returned to your account. View your order:\n%s"})
	KeyMailOrderDeadlineCancelledRefundBody = key("mail.order.cancelled.deadline.refund.body", Message{ZhHant: "訂單 %s 在保留時間內沒有完成付款，已自動取消。若有款項在期限後才到帳，已經或將會全額退還給你；若有使用購物金，已退回你的帳戶。查看訂單：\n%s", En: "Order %s was not paid while its stock was held, so it has been cancelled automatically. If a payment reached us after the deadline, it has been or will be refunded in full, and any store credit you applied has been returned to your account. View your order:\n%s"})
	KeyMailOrderStaffCancelledBody          = key("mail.order.cancelled.staff.body", Message{ZhHant: "商店已取消訂單 %s。請至訂單頁查看付款及退款狀態：\n%s", En: "The shop cancelled order %s. View its payment and refund status on the order page:\n%s"})
	KeyMailOrderStaffCancelledRefundBody    = key("mail.order.cancelled.staff.refund.body", Message{ZhHant: "很抱歉，我們取消了你的訂單 %s。若有款項已經到帳，已經或將會全額退還給你；若有使用購物金，也已退回你的帳戶。\n\n查看訂單：\n%s", En: "We are sorry: we have cancelled your order %s. If a payment reached us, it has been or will be refunded in full, and any store credit you applied has been returned to your account.\n\nView your order:\n%s"})
	KeyMailOrderDeliveredSubject            = key("mail.order.delivered.subject", Message{ZhHant: "訂單 %s 已送達", En: "Order %s has been delivered"})
	KeyMailOrderCollectedSubject            = key("mail.order.collected.subject", Message{ZhHant: "訂單 %s 已取貨", En: "Order %s has been collected"})
	KeyMailOrderDeliveredBody               = key("mail.order.delivered.body", Message{ZhHant: "訂單 %s 已標記為送達。查看訂單：\n%s", En: "Order %s has been marked as delivered. View your order:\n%s"})
	KeyMailRescissionEnds                   = key("mail.order.rescissionends", Message{ZhHant: "依消費者保護法，你可自收到商品的次日起七日內退貨，最後一日為 %s。", En: "Under Taiwan's Consumer Protection Act you may return what you bought within seven days, counted from the day after you receive the goods; the last day is %s."})
	KeyMailOrderCollectedBody               = key("mail.order.collected.body", Message{ZhHant: "訂單 %s 已標記為取貨完成。查看訂單：\n%s", En: "Order %s has been marked as collected. View your order:\n%s"})
)
