package audit

type Action string

const (
	// ActionViewCustomer is a READ, and the only one recorded here: that page's
	// entire content is somebody else's personal data.
	ActionViewCustomer             Action = "customer.view"
	ActionShipOrder                Action = "order.ship"
	ActionAdvanceOrder             Action = "order.advance"
	ActionDecideReturn             Action = "return.decide"
	ActionInspectReturn            Action = "return.inspect"
	ActionCompleteReturn           Action = "return.complete"
	ActionIssueInvoice             Action = "invoice.issue"
	ActionVoidInvoice              Action = "invoice.void"
	ActionAllowInvoice             Action = "invoice.allowance"
	ActionAuthorizeAllowanceResend Action = "invoice.allowance_resend_authorized"
	ActionReconcilePayment         Action = "payment.reconciled"
	ActionGrantCredit              Action = "credit.grant"
	ActionAdjustStock              Action = "stock.adjust"
	ActionReceiveStock             Action = "stock.receive"
	ActionPublishShipping          Action = "shipping.publish"
	ActionSetSurcharge             Action = "shipping.surcharge"
	ActionCreateTier               Action = "tier.create"
	ActionDeleteTier               Action = "tier.delete"
	ActionCorrectDelivery          Action = "order.delivery"
	ActionCreateOrderNote          Action = "order.note.create"
	ActionReplaceOrderNote         Action = "order.note.replace"
	ActionClearOrderNote           Action = "order.note.clear"
	ActionHideReview               Action = "review.hide"
	ActionShowReview               Action = "review.show"
	ActionHandleMessage            Action = "message.handle"
	ActionReopenMessage            Action = "message.reopen"
	ActionRepriceVariant           Action = "variant.reprice"
	ActionRetireVariant            Action = "variant.retire"
	ActionCreateVariant            Action = "variant.create"
	ActionCreateProduct            Action = "product.create"
	ActionUpdateProduct            Action = "product.update"
	ActionSetProductLabel          Action = "product.label.set"
	ActionSetProductInvoiceLine    Action = "product.invoice_line.set"
	ActionPublishProduct           Action = "product.status"
	ActionCreateCoupon             Action = "coupon.create"
	ActionToggleCoupon             Action = "coupon.toggle"
	ActionCreateCampaign           Action = "campaign.create"
	ActionToggleCampaign           Action = "campaign.toggle"
	ActionSetCampaignTone          Action = "campaign.tone.set"
	ActionSetCampaignWindow        Action = "campaign.window.set"
	ActionSetCategoryImage         Action = "category.image.set"
	ActionClearCategoryImage       Action = "category.image.clear"
	ActionSetCampaignImage         Action = "campaign.image.set"
	ActionClearCampaignImage       Action = "campaign.image.clear"
	ActionFeatureProduct           Action = "campaign.feature"
	ActionUnfeatureProduct         Action = "campaign.unfeature"
	ActionAddOption                Action = "option.add"
	ActionAddOptionValue           Action = "option.value.add"
	ActionAddSpec                  Action = "spec.add"
	ActionRemoveSpec               Action = "spec.remove"
	ActionAttachImage              Action = "image.attach"
	ActionDetachImage              Action = "image.detach"
	ActionSetImageOption           Action = "image.option"
	ActionMoveImage                Action = "image.move"
	ActionCreateShippingMethod     Action = "shipping.method.create"
	ActionToggleShippingMethod     Action = "shipping.method.toggle"
	ActionCreateShippingZone       Action = "shipping.zone.create"
	ActionSetZonePrefixes          Action = "shipping.zone.prefixes"
	ActionDeleteShippingZone       Action = "shipping.zone.delete"
	ActionCreateFAQ                Action = "faq.create"
	ActionUpdateFAQ                Action = "faq.update"
	ActionDeleteFAQ                Action = "faq.delete"
	ActionCreateBanner             Action = "banner.create"
	ActionToggleBanner             Action = "banner.toggle"
	ActionCreateHeroSlide          Action = "hero.create"
	ActionToggleHeroSlide          Action = "hero.toggle"
	ActionPromoteHeroSlide         Action = "hero.promote"
	ActionCreateBrand              Action = "brand.create"
	ActionRenameBrand              Action = "brand.rename"
	ActionDeleteBrand              Action = "brand.delete"
	ActionCreateCategory           Action = "category.create"
	ActionRenameCategory           Action = "category.rename"
	ActionDeleteCategory           Action = "category.delete"
	ActionAnswerQuestion           Action = "question.answer"
	ActionHideQuestion             Action = "question.hide"
	ActionShowQuestion             Action = "question.show"
	ActionHideAnswer               Action = "answer.hide"
	ActionGrantStaff               Action = "staff.grant"
	ActionRevokeStaff              Action = "staff.revoke"
	ActionRemoveStaffFactor        Action = "staff.factor.remove"
)
