package db_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func commitAttributionScript(t *testing.T) string {
	t.Helper()
	script, pathErr := filepath.Abs(filepath.Join("..", "..", "scripts", "check-commit-attribution.sh"))
	if pathErr != nil {
		t.Fatal(pathErr)
	}
	return script
}

func newCommitAttributionRepo(t *testing.T) (dir string, git func(...string) string) {
	t.Helper()
	dir = t.TempDir()
	git = func(args ...string) string {
		t.Helper()
		cmd := exec.CommandContext(t.Context(), "git", args...) //nolint:gosec // Arguments are test-owned literals and commit messages passed as data, without a shell.
		cmd.Dir = dir
		output, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("git %v: %v: %s", args, err, output)
		}
		return strings.TrimSpace(string(output))
	}
	git("init", "-q")
	git("config", "user.name", "message-test")
	git("config", "user.email", "message-test@goen.invalid")
	git("config", "commit.gpgsign", "false")
	return dir, git
}

func runCommitAttribution(t *testing.T, dir, script, base, head string, env ...string) (string, error) {
	t.Helper()
	cmd := exec.CommandContext(t.Context(), "bash", script, base, head) //nolint:gosec // Only the fixed repository script and test-owned commit SHAs execute.
	cmd.Dir = dir
	cmd.Env = append(cmd.Environ(), env...)
	output, err := cmd.CombinedOutput()
	return string(output), err
}

func TestCommitAttributionRejectsForbiddenMessages(t *testing.T) {
	script := commitAttributionScript(t)
	dir, git := newCommitAttributionRepo(t)
	git("commit", "--allow-empty", "-qm", "test: clean base")
	base := git("rev-parse", "HEAD")
	for _, tc := range []struct {
		name    string
		message string
		wantRed bool
	}{
		{"clean", "fix: preserve the native form", false},
		{"coauthor", "fix: preserve the form\n\nCo-authored-by: Someone <person@example.com>", true},
		{"owner trailer", "fix: preserve the form\n\nCo-authored-by: Koopa <Koopa0@users.noreply.github.com>", true},
		{"case and spacing", "fix: preserve the form\n\n  CO-AUTHORED-BY : Someone <person@example.com>", true},
		{"inline attribution", "fix: preserve the form Co-authored-by: Someone", true},
		{"self identification", "fix: written by Cursor", true},
		{"agent identity", "fix: preserve the form\n\nCursor Agent", true},
		{"generated attribution", "fix: generated by Cursor", true},
		{"other generated attribution", "fix: generated by Codex", true},
		{"large message", "fix: preserve the form\n\nCo-authored-by: Someone\n" + strings.Repeat("body\n", 20000), true},
	} {
		t.Run("available base/"+tc.name, func(t *testing.T) {
			git("commit", "--allow-empty", "-qm", tc.message)
			head := git("rev-parse", "HEAD")
			output, err := runCommitAttribution(t, dir, script, base, head)
			if (err != nil) != tc.wantRed {
				t.Fatalf("want red=%t, got %v: %s", tc.wantRed, err, output)
			}
			if tc.wantRed && !strings.Contains(output, "forbidden attribution") {
				t.Fatalf("not an attribution failure: %s", output)
			}
			base = head
		})
	}
}

func TestCommitAttributionScansReachableHistory(t *testing.T) {
	script := commitAttributionScript(t)
	missingBase := strings.Repeat("f", 40)
	zeroBase := strings.Repeat("0", 40)

	t.Run("available base range", func(t *testing.T) {
		dir, git := newCommitAttributionRepo(t)
		git("commit", "--allow-empty", "-qm", "test: clean root")
		base := git("rev-parse", "HEAD")
		git("commit", "--allow-empty", "-qm", "fix: preserve the form\n\nCo-authored-by: Someone <person@example.com>")
		git("commit", "--allow-empty", "-qm", "fix: clean tip")
		head := git("rev-parse", "HEAD")
		output, err := runCommitAttribution(t, dir, script, base, head)
		if err == nil || !strings.Contains(output, "forbidden attribution") {
			t.Fatalf("available-base range must reject dirty ancestor: %v: %s", err, output)
		}
	})

	t.Run("zero base initial push", func(t *testing.T) {
		dir, git := newCommitAttributionRepo(t)
		git("commit", "--allow-empty", "-qm", "test: clean root")
		git("commit", "--allow-empty", "-qm", "fix: preserve the form\n\nCo-authored-by: Someone <person@example.com>")
		head := git("rev-parse", "HEAD")
		output, err := runCommitAttribution(t, dir, script, zeroBase, head)
		if err == nil || !strings.Contains(output, "forbidden attribution") {
			t.Fatalf("zero-base scan must reject dirty ancestor: %v: %s", err, output)
		}
	})

	t.Run("missing base clean history", func(t *testing.T) {
		dir, git := newCommitAttributionRepo(t)
		git("commit", "--allow-empty", "-qm", "test: clean root")
		git("commit", "--allow-empty", "-qm", "fix: clean tip")
		head := git("rev-parse", "HEAD")
		output, err := runCommitAttribution(t, dir, script, missingBase, head)
		if err != nil {
			t.Fatalf("missing base must pass on clean history: %v: %s", err, output)
		}
		if !strings.Contains(output, "PASS") {
			t.Fatalf("missing base must pass on clean history: %s", output)
		}
	})

	t.Run("missing base dirty ancestor clean tip", func(t *testing.T) {
		dir, git := newCommitAttributionRepo(t)
		git("commit", "--allow-empty", "-qm", "test: clean root")
		git("commit", "--allow-empty", "-qm", "fix: preserve the form\n\nCo-authored-by: Someone <person@example.com>")
		git("commit", "--allow-empty", "-qm", "fix: clean tip")
		head := git("rev-parse", "HEAD")
		output, err := runCommitAttribution(t, dir, script, missingBase, head)
		if err == nil || !strings.Contains(output, "forbidden attribution") {
			t.Fatalf("missing base must reject dirty ancestor: %v: %s", err, output)
		}
	})

	t.Run("missing base dirty tip", func(t *testing.T) {
		dir, git := newCommitAttributionRepo(t)
		git("commit", "--allow-empty", "-qm", "test: clean root")
		git("commit", "--allow-empty", "-qm", "fix: generated by Cursor")
		head := git("rev-parse", "HEAD")
		output, err := runCommitAttribution(t, dir, script, missingBase, head)
		if err == nil || !strings.Contains(output, "forbidden attribution") {
			t.Fatalf("missing base must reject dirty tip: %v: %s", err, output)
		}
	})
}

func TestCommitAttributionFailsClosedOnInputAndDetectorErrors(t *testing.T) {
	script := commitAttributionScript(t)
	dir, git := newCommitAttributionRepo(t)
	git("commit", "--allow-empty", "-qm", "test: clean base")
	base := git("rev-parse", "HEAD")
	head := base

	output, err := runCommitAttribution(t, dir, script, "not-a-sha", head)
	if err == nil || !strings.Contains(output, "two full commit SHAs are required") {
		t.Fatalf("malformed SHA must fail closed: %v: %s", err, output)
	}

	output, err = runCommitAttribution(t, dir, script, base, strings.Repeat("a", 40))
	if err == nil {
		t.Fatalf("missing head must fail closed: %v: %s", err, output)
	}

	fixture := filepath.Join(dir, "failing-grep.sh")
	if writeErr := os.WriteFile(fixture, []byte("grep() { return 2; }\n"), 0o600); writeErr != nil {
		t.Fatal(writeErr)
	}
	git("commit", "--allow-empty", "-qm", "test: clean detector input")
	output, err = runCommitAttribution(t, dir, script, base, git("rev-parse", "HEAD"), "BASH_ENV="+fixture)
	if err == nil || !strings.Contains(output, "detector failed") {
		t.Fatalf("detector error must fail closed, got %v: %s", err, output)
	}
}
